steps:
  - name: 'node'
    entrypoint: 'bash'
    id: 'npm-run-build'
    args:
      - '-c'
      - |
        pwd \
        && ls \
        && cd gains-tracker-ui \
        && npm install \
        && npm run build
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    waitFor:
      - 'npm-run-build'
    args:
      - '-c'
      - |
        gcloud config set app/cloud_build_timeout 1600 \
        && cd gains-tracker-ui \
        && gcloud app deploy -v 1 \
        && cd ../backend \
        && gcloud app deploy -v 1
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY