version: '2'

services:
  postgres:
    container_name: postgres
    build:
      context: ./database
    environment:
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
    networks:
      - default
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
    - 8000:8000
    networks:
      - default
