runtime: python39
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker main:app
automatic_scaling:
  max_instances: 1
env_variables:
  DATABASE_HOST: "/cloudsql/f2023-ece528-group7:us-east1:database"